# Generated by Django 5.2 on 2026-01-17 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The datetime this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated')),
                ('portal_id', models.CharField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('description', models.TextField()),
                ('applicants', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('query_id', models.IntegerField(blank=True, default=None, null=True)),
                ('portal', models.CharField(choices=[('linkedin', 'Linkedin'), ('indeed', 'Indeed'), ('stack', 'Stack Overflow')], default='linkedin', max_length=20)),
                ('salary', models.CharField(blank=True, default=None, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExtendedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The datetime this object was created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The datetime this object was last updated')),
                ('bachelor_required', models.BooleanField()),
                ('master_required', models.BooleanField()),
                ('phd_required', models.BooleanField()),
                ('tech_stack', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('min_experience_years', models.IntegerField(blank=True, default=None, null=True)),
                ('us_only', models.BooleanField()),
                ('salary', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('employment_type', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('medical_insurance', models.BooleanField()),
                ('hourprice', models.FloatField(blank=True, default=None, null=True)),
                ('salary_currency', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
