# Generated by Django 5.2 on 2026-01-31 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_load_jobs_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendedjob',
            name='job_category',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
