# Generated by Django 5.2 on 2026-01-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_extendedjob_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendedjob',
            name='bachelor_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extendedjob',
            name='master_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extendedjob',
            name='medical_insurance',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extendedjob',
            name='phd_required',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='extendedjob',
            name='us_only',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
